### ISSUE TITLE
Keep URL updated

### ISSUE THREAD

**Issue by mortenjust** [auchenberg/timey#15]
Let users find a good time and copy it to paste it into an email or IM

Example: User has 3 timezones in the list. London, Copenhagen, San Francisco. 
- Upon loading the page, the url becomes local-time.in/London+United+Kingdom/9:30pm
- The string is the top line from Maps autocomplete which seems to be unique
- Ideally, the city in the URL is the user's own city, but low priority. We can pick the city at the top for now.
- The URL updates when the time updates
- Changing the time in the application stops the updater and adds that time to the url
- Clicking this URL will add London UK and set the time to 9:30pm in London UK
- If the user already has London UK in the list, don't add it 

If this is too complex, we can use latlon or another ID, just to get the linking going

**Comment by auchenberg** [comment]
Implemented, with the exception of hour:minute, as changing the URL (pushStates) removes focus from the input field, which gives an annoying experience.
